-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emailVerified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emailOtpHash" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emailOtpExpiresAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emailOtpLastSentAt" TIMESTAMP(3);
