ALTER TYPE "ServiceBookingStatus" ADD VALUE IF NOT EXISTS 'ON_THE_WAY';

ALTER TABLE "ServiceBooking" ADD COLUMN IF NOT EXISTS "destinationLat" DOUBLE PRECISION;
ALTER TABLE "ServiceBooking" ADD COLUMN IF NOT EXISTS "destinationLng" DOUBLE PRECISION;
ALTER TABLE "ServiceBooking" ADD COLUMN IF NOT EXISTS "providerLat" DOUBLE PRECISION;
ALTER TABLE "ServiceBooking" ADD COLUMN IF NOT EXISTS "providerLng" DOUBLE PRECISION;
ALTER TABLE "ServiceBooking" ADD COLUMN IF NOT EXISTS "providerLocationUpdatedAt" TIMESTAMP(3);
ALTER TABLE "ServiceBooking" ADD COLUMN IF NOT EXISTS "trackingActive" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ServiceBooking" ADD COLUMN IF NOT EXISTS "enRouteAt" TIMESTAMP(3);
