-- AlterTable
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "epcCurrentScore" INTEGER;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "epcPotentialScore" INTEGER;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "furnishType" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "garden" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "parkingType" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "accessibility" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "keyFeatures" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "utilities" JSONB;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "broadbandSpeed" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "floodRisk" TEXT;
