ALTER TABLE "AdminSettings" ADD COLUMN IF NOT EXISTS "serviceTaxPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "AdminSettings" ADD COLUMN IF NOT EXISTS "serviceBookingFee" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "AdminSettings" ADD COLUMN IF NOT EXISTS "serviceExtraFeeLabel" TEXT NOT NULL DEFAULT '';
ALTER TABLE "AdminSettings" ADD COLUMN IF NOT EXISTS "serviceExtraFeeAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
