-- Add Service Document Types to DocumentType enum
-- Migration: Add SERVICE_CERTIFICATE, SERVICE_LICENSE, SERVICE_SKILL_CERTIFICATE, SERVICE_EXPERIENCE_LETTER, SERVICE_TRAINING_CERTIFICATE

-- Add new enum values for Service Role Documents
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'SERVICE_CERTIFICATE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'SERVICE_LICENSE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'SERVICE_SKILL_CERTIFICATE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'SERVICE_EXPERIENCE_LETTER';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'SERVICE_TRAINING_CERTIFICATE';
