ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bankAccountHolder" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bankSortCode" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bankAccountNumber" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bankName" TEXT;
