ALTER TABLE "CatalogService" ADD COLUMN IF NOT EXISTS "morningSurcharge" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "CatalogService" ADD COLUMN IF NOT EXISTS "afternoonSurcharge" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "CatalogService" ADD COLUMN IF NOT EXISTS "eveningSurcharge" DOUBLE PRECISION NOT NULL DEFAULT 0;
